insert into courses(`CourseID`,`name`, `title`,`description`) values (NULL,'ITP 120', 'JAVA Programming I','description');
insert into courses(`CourseID`,`name`, `title`,`description`) values (NULL,'ITP 112', 'Visual Basic.NET I','description');
insert into courses(`CourseID`,`name`, `title`,`description`) values (NULL,'ITP 120', 'JAVA Programming I','description');
insert into courses(`CourseID`,`name`, `title`,`description`) values (NULL,'ITP 130', 'C Programming I','description');
insert into courses(`CourseID`,`name`, `title`,`description`) values (NULL,'ITP 132', 'C++ Programming I','description');
insert into courses(`CourseID`,`name`, `title`,`description`) values (NULL,'ITP 136', 'C# Programming I','description');
insert into courses(`CourseID`,`name`, `title`,`description`) values (NULL,'ITP 137', 'Programming IOS Devices','description');
insert into courses(`CourseID`,`name`, `title`,`description`) values (NULL,'ITP 165', 'Gaming and Simulation','description');
insert into courses(`CourseID`,`name`, `title`,`description`) values (NULL,'ITP 170', 'Project Management','description');
insert into courses(`CourseID`,`name`, `title`,`description`) values (NULL,'ITP 193', 'Studies in','description');
insert into courses(`CourseID`,`name`, `title`,`description`) values (NULL,'ITP 196', 'On-Site Training in','description');
insert into courses(`CourseID`,`name`, `title`,`description`) values (NULL,'ITP 197', 'Cooperative Education','description');
insert into courses(`CourseID`,`name`, `title`,`description`) values (NULL,'ITP 198', 'Seminar & Project','description');
insert into courses(`CourseID`,`name`, `title`,`description`) values (NULL,'ITP 199', 'Supervised Study','description');
insert into courses(`CourseID`,`name`, `title`,`description`) values (NULL,'ITP 220', 'Java Programming II','description');
insert into courses(`CourseID`,`name`, `title`,`description`) values (NULL,'ITP 225', 'Web Scripting Languages','description');
insert into courses(`CourseID`,`name`, `title`,`description`) values (NULL,'ITP 226', 'Mobile Java Development','description');
insert into courses(`CourseID`,`name`, `title`,`description`) values (NULL,'ITP 230', 'C Programming II','description');
insert into courses(`CourseID`,`name`, `title`,`description`) values (NULL,'ITP 234', 'Visual C++ Programming','description');
insert into courses(`CourseID`,`name`, `title`,`description`) values (NULL,'ITP 236', 'C# Programming II','description');
insert into courses(`CourseID`,`name`, `title`,`description`) values (NULL,'ITP 244', 'ASP.NET- Server Side Programming','description');
insert into courses(`CourseID`,`name`, `title`,`description`) values (NULL,'ITP 246', 'Internet Devel. II: Server-Side JAVA','description');
insert into courses(`CourseID`,`name`, `title`,`description`) values (NULL,'ITP 251', 'System Analysis and Design','description');
insert into courses(`CourseID`,`name`, `title`,`description`) values (NULL,'ITP 270', 'Programming For Cybersecurity','description');
insert into courses(`CourseID`,`name`, `title`,`description`) values (NULL,'ITP 293', 'Studies in','description');
insert into courses(`CourseID`,`name`, `title`,`description`) values (NULL,'ITP 296', 'On-Site Training in','description');
insert into courses(`CourseID`,`name`, `title`,`description`) values (NULL,'ITP 297', 'Cooperative Education','description');
insert into courses(`CourseID`,`name`, `title`,`description`) values (NULL,'ITP 298', 'Seminar & Project','description');